spring.application.name=product-service
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Tambahkan baris ini untuk ganti nama instance
eureka.instance.instance-id=sonya:product-service:8081